travis:
  secure:
    BINSTAR_TOKEN: uDiVDcL7110c+f0wLSsewPnGfwwE/Yt/nPYhHZKt473r41+mtAOJqPkcsaVJgewvSSpACQCcirGvi8R+o1SHKCRAIK1kxB7Z5uMXcaaeibqeD8YYBJbnl6uRa/rn6kjCN89xcPjACSQd+rQpxuqmU+/eZ32OIqb27VILgyyHKV4p2W679YzAer1LiB/XbeSdpGkenhkcxe8qEEkWsgfSh2Jr2FC+bXPV2T1FuPA49A1GSqFqnHCu5v6UaOC1IRQwQn3wek+hYEChMV4XHO4Xm0fUdUIp2eSBxeHshcKFP2dXl7ZstAMx5Zrs83TCk4VTFSlhU2G/Crgp1v1sPkS6Y6iqtCOdIXjuHhISZPxiVrD/mJUFVb2O5lAdb2ACvtrfjfKuQtSrtnxdt6U6VqbfUiqinVf9zURCM+9XjewUCLA9/R7U4RfSRaCysjro4ODKcyIpg/ZaX6/axVSBBQsggoc3UXoPZ049qlC+2jxaD6Cob5AGgSI0t5OnWfWpjN9uW+AiuaYg8fTutQA1XO/ioohl4q6lmRmG/ZgKMcwaxWnpXgSWyLjJlA3ZEu0itJCquLWXHAg5DrXc66DRPMdekOcS9KhRqinsWd54GrUpJ0nS4l7ipFHwW+M+sBAvBjl3fkV8be0NZQ9246Tc0+XsyNRUcGM6ErF8y6WZx9Dio3Y=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
conda_forge_output_validation: true
